import json
import os
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer

PORT = 8099

_APP_DIR  = os.path.dirname(os.path.abspath(__file__))
_ENV_FILE = os.path.join(os.path.dirname(_APP_DIR), ".env")
_TMPL_DIR = os.path.join(_APP_DIR, "templates")

_setup_done = threading.Event()
_server: HTTPServer | None = None
_server_lock = threading.Lock()


# ── helpers ──────────────────────────────────────────────────────────────────

def _read_env_file() -> dict:
    values = {}
    if not os.path.exists(_ENV_FILE):
        return values
    try:
        with open(_ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    values[key.strip()] = val.strip()
    except OSError:
        pass
    return values


def _write_env_file(data: dict):
    lines = [
        "# Release Monitor — generated by setup wizard",
        "",
        f"REPOS={data.get('REPOS', '')}",
        f"GITLAB_REPOS={data.get('GITLAB_REPOS', '')}",
        f"GOOGLE_CHAT_WEBHOOK={data.get('GOOGLE_CHAT_WEBHOOK', '')}",
        f"GITHUB_TOKEN={data.get('GITHUB_TOKEN', '')}",
        f"GITLAB_TOKEN={data.get('GITLAB_TOKEN', '')}",
        f"GITLAB_URL={data.get('GITLAB_URL', 'https://gitlab.com')}",
        f"INTERVAL_MINUTES={data.get('INTERVAL_MINUTES', '60')}",
        f"IGNORE_PRERELEASE={data.get('IGNORE_PRERELEASE', 'true')}",
        f"TIMEZONE={data.get('TIMEZONE', 'UTC')}",
        f"STATE_FILE={data.get('STATE_FILE', '/app/data/state.json')}",
    ]
    with open(_ENV_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


def _load_into_environ(data: dict):
    for key, value in data.items():
        if value:
            os.environ[key] = value


def _render_setup(mode: str = "setup") -> bytes:
    with open(os.path.join(_TMPL_DIR, "setup.html"), encoding="utf-8") as f:
        html = f.read()
    html = html.replace("__EXISTING__", json.dumps(_read_env_file()))
    html = html.replace('"__MODE__"', json.dumps(mode))
    return html.encode("utf-8")


def _render_status() -> bytes:
    with open(os.path.join(_TMPL_DIR, "status.html"), encoding="utf-8") as f:
        return f.read().encode("utf-8")


def _build_status_json() -> dict:
    from app.config import REPOS, GITLAB_REPOS, GITLAB_URL, INTERVAL_MINUTES, IGNORE_PRERELEASE, TIMEZONE
    from app.state import get_all_repos_state

    state = get_all_repos_state()
    repos_data = []

    def _entry(repo: str, state_key: str, url: str, source: str):
        entry = state.get(state_key)
        last_release = None
        last_checked = None
        if isinstance(entry, dict) and entry.get("tag_name"):
            last_release = {
                "tag_name":    entry["tag_name"],
                "published_at": entry.get("published_at"),
                "html_url":    entry.get("html_url"),
            }
            last_checked = entry.get("last_checked")
        return {"name": repo, "url": url, "source": source,
                "last_release": last_release, "last_checked": last_checked}

    for repo in REPOS:
        repos_data.append(_entry(repo, repo, f"https://github.com/{repo}", "github"))

    for repo in GITLAB_REPOS:
        repos_data.append(_entry(repo, f"gitlab:{repo}", f"{GITLAB_URL}/{repo}", "gitlab"))

    return {
        "repos": repos_data,
        "config": {
            "interval_minutes": INTERVAL_MINUTES,
            "ignore_prerelease": IGNORE_PRERELEASE,
            "timezone": TIMEZONE,
        },
    }


def needs_setup() -> bool:
    has_repos = bool(os.getenv("REPOS") or os.getenv("GITLAB_REPOS"))
    return not has_repos or not os.getenv("GOOGLE_CHAT_WEBHOOK")


# ── HTTP handler ──────────────────────────────────────────────────────────────

class _Handler(BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        pass

    def do_GET(self):
        if self.path in ("/", "/status"):
            if not _setup_done.is_set():
                self._respond(200, "text/html", _render_setup("setup"))
            else:
                self._respond(200, "text/html", _render_status())

        elif self.path == "/configure":
            self._respond(200, "text/html", _render_setup("reconfigure"))

        elif self.path == "/api/status":
            try:
                body = json.dumps(_build_status_json()).encode()
                self._respond(200, "application/json", body)
            except Exception:
                self._respond(500, "application/json", b'{"error":"not ready"}')

        elif self.path == "/logo.svg":
            path = os.path.join(_TMPL_DIR, "logo.svg")
            with open(path, "rb") as f:
                self._respond(200, "image/svg+xml", f.read())

        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if self.path != "/save":
            self.send_response(404)
            self.end_headers()
            return

        length = int(self.headers.get("Content-Length", 0))
        data = json.loads(self.rfile.read(length))

        _write_env_file(data)
        _load_into_environ(data)

        body = json.dumps({"ok": True}).encode()
        self._respond(200, "application/json", body)

        _setup_done.set()

    def _respond(self, status: int, content_type: str, body: bytes):
        self.send_response(status)
        self.send_header("Content-Type", f"{content_type}; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


# ── public API ────────────────────────────────────────────────────────────────

def _ensure_server():
    global _server
    with _server_lock:
        if _server is not None:
            return
        _server = HTTPServer(("localhost", PORT), _Handler)
        t = threading.Thread(target=_server.serve_forever, daemon=True)
        t.start()


def run_setup_wizard():
    if not needs_setup():
        _setup_done.set()
        return

    _ensure_server()

    url = f"http://localhost:{PORT}"
    print(f"\n  Setup required. Opening {url} in your browser...")
    print("  If the browser doesn't open, navigate to the URL manually.\n")
    webbrowser.open(url)

    _setup_done.wait()
    print("  Configuration saved. Starting Release Monitor...\n")


def start_status_server():
    _ensure_server()
    print(f"  Status page: http://localhost:{PORT}\n")
